version: "3.7"

services:
  app:
    volumes:
      - static:/static
    env_file:
      - ./app/.env
    build:
      context: ./app
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static: