version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 5000:5000
    command: >
      sh -c " sleep infinity &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:5000"
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace