version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    command: sleep infinity
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace